// <auto-generated />
using System;
using CoffeeMaster.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoffeeMaster.Migrations
{
    [DbContext(typeof(CoffeeMasterContext))]
    [Migration("20211206150151_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoffeeMaster.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarChar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rewards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CoffeeMaster.Models.OrderManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsServed")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderCustomerId")
                        .HasColumnType("int");

                    b.Property<int>("RewardValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderCustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeMaster.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarChar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarChar(100)");

                    b.Property<int?>("OrderManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderManagerId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderManagerId");

                    b.HasIndex("OrderManagerId1");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CoffeeMaster.Models.OrderManager", b =>
                {
                    b.HasOne("CoffeeMaster.Models.Customer", "OrderCustomer")
                        .WithMany()
                        .HasForeignKey("OrderCustomerId");

                    b.Navigation("OrderCustomer");
                });

            modelBuilder.Entity("CoffeeMaster.Models.Product", b =>
                {
                    b.HasOne("CoffeeMaster.Models.OrderManager", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderManagerId");

                    b.HasOne("CoffeeMaster.Models.OrderManager", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderManagerId1");
                });

            modelBuilder.Entity("CoffeeMaster.Models.OrderManager", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
